 platform :ios, ‘9.0’
use_frameworks!

target 'LSHOpenYourEyes' do
  pod 'AFNetworking', '~> 2.5.3'
  pod 'SDWebImage', '~> 3.7.2'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'MagicalRecord', '~> 2.3.2'
  pod 'JSONModel', '~> 1.2.0'
  pod 'DJRefresh', '~> 1.0.5'
  pod 'FMDB', '~> 2.6.2'
end